spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dabjeongneo
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: 127.0.0.1 #이 주소는 네트워크 상에서 항상 자신의 컴퓨터를 가리킴
    port: 6379
    password: asdf



jwt:
  header: Authorization
  prefix: Bearer
  secret: ${JWT_SECRET:eaffagdgasheweasdf}
  access-exp: 12000
  refresh-exp: 24000


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  level:
    root: INFO
    com.example.studykotlin: DEBUG
    org.springframework.data.redis: DEBUG

